name: Cinder OSS Build and Test

on: [push]

env:
  REGISTRY: ghcr.io
  CINDER_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/cinder

jobs:
  cinder-oss-build-and-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for pre-test Cinder Docker image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.CINDER_IMAGE_NAME }}
          # we publish the [untested] image using the branch + sha (e.g. "cinder-3.8.162db45") for debuggability
          # note: `/` in the branch name (e.g "cinder/3.8") are auto-converted to `-` by this action
          tags: type=sha,prefix={{branch}}.
      - name: Build and push Cinder Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          target: build
          file: .github/workflows/cinder/Dockerfile
      - name: Run Cinder Tests
        run: docker run --rm -w /cinder ${{ steps.meta.outputs.tags }} ./oss-cinder-test.sh
      - name: Extract metadata for tested Cinder Docker image push
        id: metapush
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.CINDER_IMAGE_NAME }}
          # once the image passes tests, we also publish it using the branch name (e.g. "cinder-3.8")
          # if this is the default branch, we also publish the image as "latest"
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      # This step publishes the image built in the previous step (all layers are cached)
      - name: Publish new version of latest Cinder Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.metapush.outputs.tags }}
          labels: ${{ steps.metapush.outputs.labels }}
          target: runtime
          file: .github/workflows/cinder/Dockerfile

  cinder-explorer-app-job:
    runs-on: ubuntu-latest
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    needs: cinder-oss-build-and-test-job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Cinder Explorer app Docker image push
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.CINDER_IMAGE_NAME }}
          tags: |
            type=sha,prefix={{branch}}.
            type=ref,event=branch
            type=raw,value=latest
      - name: Build and Push Cinder Explorer Docker Images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: explorer
          file: .github/workflows/cinder/Dockerfile
